In [20]:
import boto3
import gzip
import pandas as pd
from io import BytesIO

In [2]:
s3_client = boto3.client('s3')

In [3]:
response = s3_client.get_object(Bucket='atc-speech-recognition', Key='readsb-hist/2022/01/08/000000Z.json.gz')

In [92]:
s3 = boto3.resource("s3")
obj = s3.Object("atc-speech-recognition", "readsb-hist/2022/01/08/000000Z.json.gz")
with gzip.GzipFile(fileobj=obj.get()["Body"]) as gzipfile:
    content = gzipfile.read()

In [55]:
json_file = json.loads(content)['aircraft']

In [59]:
df = pd.DataFrame.from_dict(json_file)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8211 entries, 0 to 8210
Data columns (total 56 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hex               8211 non-null   object
 1   type              8211 non-null   object
 2   flight            7421 non-null   object
 3   r                 7411 non-null   object
 4   t                 7350 non-null   object
 5   alt_baro          7880 non-null   object
 6   alt_geom          5945 non-null   float64
 7   gs                7488 non-null   float64
 8   track             6687 non-null   float64
 9   baro_rate         5007 non-null   float64
 10  squawk            6702 non-null   object
 11  emergency         6055 non-null   object
 12  category          7133 non-null   object
 13  nav_qnh           4673 non-null   float64
 14  nav_altitude_mcp  4712 non-null   float64
 15  nav_heading       2611 non-null   float64
 16  lat               7377 non-null   float64
 17  lon               7377 non-null   float64
 18  nic               7377 non-null   float64
 19  rc                7377 non-null   float64
 20  seen_pos          7377 non-null   float64
 21  version           7069 non-null   float64
 22  nic_baro          5506 non-null   float64
 23  nac_p             7162 non-null   float64
 24  nac_v             6938 non-null   float64
 25  sil               7162 non-null   float64
 26  sil_type          7945 non-null   object
 27  gva               5423 non-null   float64
 28  sda               6142 non-null   float64
 29  alert             6672 non-null   float64
 30  spi               6672 non-null   float64
 31  mlat              8211 non-null   object
 32  tisb              8211 non-null   object
 33  messages          8211 non-null   int64
 34  seen              8211 non-null   float64
 35  rssi              8211 non-null   float64
 36  geom_rate         2739 non-null   float64
 37  nav_modes         767 non-null    object
 38  dbFlags           207 non-null    float64
 39  lastPosition      476 non-null    object
 40  true_heading      1845 non-null   float64
 41  nav_altitude_fms  360 non-null    float64
 42  calc_track        96 non-null     float64
 43  ias               1197 non-null   float64
 44  tas               1189 non-null   float64
 45  mach              1196 non-null   float64
 46  wd                1063 non-null   float64
 47  ws                1063 non-null   float64
 48  oat               1016 non-null   float64
 49  tat               1016 non-null   float64
 50  track_rate        1015 non-null   float64
 51  roll              1184 non-null   float64
 52  mag_heading       1263 non-null   float64
 53  rr_lat            334 non-null    float64
 54  rr_lon            334 non-null    float64
 55  gpsOkBefore       4 non-null      float64
dtypes: float64(41), int64(1), object(14)
memory usage: 3.5+ MB

In [88]:
df[(df['lat']-32.8998)**2+(df['lon']+97.0403)**2<6.25]

,hex,type,flight,r,t,alt_baro,alt_geom,gs,track,baro_rate,...,wd,ws,oat,tat,track_rate,roll,mag_heading,rr_lat,rr_lon,gpsOkBefore
2230,a289ec,adsb_icao,N2628S,N2628S,C337,9600,9650.0,162.4,130.75,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2235,a1716c,adsb_icao,JUS192,N192US,DC91,34000,34925.0,424.1,271.35,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2238,ad0520,adsb_icao,FTH938,N938TX,C750,43000,44100.0,481.3,287.91,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2269,ac9ec4,adsb_icao,N912GW,N912GW,C25A,41000,41975.0,435.8,125.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2273,a93ac8,adsb_icao,NKS1466,N694NK,A320,39025,40025.0,480.4,109.45,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2783,a64d1e,adsb_icao,N505GE,N505GE,BE60,8300,8500.0,184.8,345.59,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2797,aa234a,adsb_icao,AAL1043,N752US,A319,36075,36925.0,453.8,83.67,1280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2812,a36f9d,adsb_icao,N320PH,N320PH,EC35,1150,1275.0,96.0,180.60,512.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2822,a448d7,adsb_icao,UAL745,N37508,B39M,34000,34950.0,472.0,306.99,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2827,aad762,adsb_icao,SWA1830,N798SW,B737,37000,37925.0,465.8,101.77,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
df[df['lon']<20]

,hex,type,flight,r,t,alt_baro,alt_geom,gs,track,baro_rate,...,wd,ws,oat,tat,track_rate,roll,mag_heading,rr_lat,rr_lon,gpsOkBefore
0,a7fa65,adsb_icao,FDX5285,N613FE,MD11,36025,35350.0,495.4,249.81,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a806d8,adsb_icao,UPS64,N616UP,B748,38000,37275.0,497.7,249.78,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a6456d,adsb_icao,DAL27,N503DN,A359,38000,37000.0,524.2,278.11,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a4c34c,adsb_icao,DAL197,N406DX,A339,36000,35025.0,520.2,278.85,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,a31a54,adsb_icao,UAL893,N29975,B789,37000,36000.0,522.1,268.79,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6315,474805,adsb_icao_nt,TXLU04,NaN,NaN,ground,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6316,4d010b,adsb_icao,ICV8799,LX-VCV,B744,34000,33350.0,453.8,278.36,0.0,...,228.0,31.0,-57.0,-28.0,-0.03,-0.35,270.53,NaN,NaN,NaN
6317,471f75,adsb_icao,WZZ84WX,HA-LXT,A321,39025,38350.0,450.5,119.52,-64.0,...,226.0,34.0,-55.0,-29.0,-0.03,-0.35,118.48,NaN,NaN,NaN
6318,471f64,adsb_icao,WZZ1EE,HA-LXC,A321,2025,2275.0,155.0,312.65,-704.0,...,109.0,9.0,NaN,NaN,0.28,0.18,308.67,NaN,NaN,NaN
6319,471f56,adsb_icao,WZZ86CF,HA-LWO,A320,39050,38200.0,452.1,116.40,0.0,...,227.0,46.0,-57.0,-31.0,0.00,0.00,116.19,NaN,NaN,NaN

In [105]:
df_combined = pd.DataFrame()

In [106]:
df_combined.append(df)

,hex,type,flight,r,t,alt_baro,alt_geom,gs,track,baro_rate,...,wd,ws,oat,tat,track_rate,roll,mag_heading,rr_lat,rr_lon,gpsOkBefore
0,a7fa65,adsb_icao,FDX5285,N613FE,MD11,36025,35350.0,495.4,249.81,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a806d8,adsb_icao,UPS64,N616UP,B748,38000,37275.0,497.7,249.78,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a6456d,adsb_icao,DAL27,N503DN,A359,38000,37000.0,524.2,278.11,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a4c34c,adsb_icao,DAL197,N406DX,A339,36000,35025.0,520.2,278.85,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,a31a54,adsb_icao,UAL893,N29975,B789,37000,36000.0,522.1,268.79,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8206,a37845,mode_s,N3221M,N3221M,BE9L,ground,7650.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.6,-106.1,NaN
8207,461f4e,mode_s,NaN,OH-LWG,A359,NaN,NaN,360.6,65.07,-2368.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.1,127.1,NaN
8208,4846e7,adsb_icao_nt,OH67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8209,4243a3,adsb_icao,NaN,VP-BZC,E190,NaN,NaN,219.0,359.74,-448.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8210,~338bce,tisb_other,NaN,NaN,NaN,ground,NaN,16.5,312.19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
d = {'col1': [1, 2], 'col2': [3, 4], 'flight': ['yoyo','hello']}
df_2 = pd.DataFrame(data=d)

In [113]:
df.append(df_2)

,hex,type,flight,r,t,alt_baro,alt_geom,gs,track,baro_rate,...,oat,tat,track_rate,roll,mag_heading,rr_lat,rr_lon,gpsOkBefore,col1,col2
0,a7fa65,adsb_icao,FDX5285,N613FE,MD11,36025,35350.0,495.4,249.81,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a806d8,adsb_icao,UPS64,N616UP,B748,38000,37275.0,497.7,249.78,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a6456d,adsb_icao,DAL27,N503DN,A359,38000,37000.0,524.2,278.11,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a4c34c,adsb_icao,DAL197,N406DX,A339,36000,35025.0,520.2,278.85,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,a31a54,adsb_icao,UAL893,N29975,B789,37000,36000.0,522.1,268.79,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8208,4846e7,adsb_icao_nt,OH67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8209,4243a3,adsb_icao,NaN,VP-BZC,E190,NaN,NaN,219.0,359.74,-448.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8210,~338bce,tisb_other,NaN,NaN,NaN,ground,NaN,16.5,312.19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,yoyo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0
1,NaN,NaN,hello,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0

In [115]:
df['time'] = json.loads(content)['now']

In [116]:
df

,hex,type,flight,r,t,alt_baro,alt_geom,gs,track,baro_rate,...,ws,oat,tat,track_rate,roll,mag_heading,rr_lat,rr_lon,gpsOkBefore,time
0,a7fa65,adsb_icao,FDX5285,N613FE,MD11,36025,35350.0,495.4,249.81,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.641600e+09
1,a806d8,adsb_icao,UPS64,N616UP,B748,38000,37275.0,497.7,249.78,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.641600e+09
2,a6456d,adsb_icao,DAL27,N503DN,A359,38000,37000.0,524.2,278.11,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.641600e+09
3,a4c34c,adsb_icao,DAL197,N406DX,A339,36000,35025.0,520.2,278.85,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.641600e+09
4,a31a54,adsb_icao,UAL893,N29975,B789,37000,36000.0,522.1,268.79,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.641600e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8206,a37845,mode_s,N3221M,N3221M,BE9L,ground,7650.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,37.6,-106.1,NaN,1.641600e+09
8207,461f4e,mode_s,NaN,OH-LWG,A359,NaN,NaN,360.6,65.07,-2368.0,...,NaN,NaN,NaN,NaN,NaN,NaN,38.1,127.1,NaN,1.641600e+09
8208,4846e7,adsb_icao_nt,OH67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.641600e+09
8209,4243a3,adsb_icao,NaN,VP-BZC,E190,NaN,NaN,219.0,359.74,-448.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.641600e+09
8210,~338bce,tisb_other,NaN,NaN,NaN,ground,NaN,16.5,312.19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.641600e+09